### ISSUE TITLE
Move environment variable definitions to separate files

### ISSUE THREAD

**Issue by alejandro-colomar** [alejandro-colomar/rob_cam#14]
Pending:

 - Docker: move definitions to key=value file

**Comment by alejandro-colomar** [comment]
https://github.com/alejandro-colomar/rob_cam/tree/patch-a1

First attempt

@secobau check it

**Comment by secobau** [comment]
You did not change docker-compose.yaml in your PR. Then you should modify the title of the issue and explicitly mention Kubernetes because docker-compose will follow.

**Comment by alejandro-colomar** [comment]
There is no PR yet, only a patch and an issue, and the patch already mentions kubernetes.  Yes, the docker-compose will follow.  And that can be discussed in this same issue, so the generic name can be used for both.

**Comment by secobau** [comment]
https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/

**Comment by secobau** [comment]
I understand we are going to encrypt the secret.yaml file but that would include the metadata which could give a hint to a possible crypto attack. To avoid that risk it is preferable to use this approach:

- https://kubernetes.io/docs/concepts/configuration/secret/#creating-a-secret-from-a-generator

**Comment by alejandro-colomar** [comment]
https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/

**Comment by alejandro-colomar** [comment]
docker-compose is still pending

**Comment by secobau** [comment]
docker-compose is not really handling secrets outside of Swarm. There is a "fake" secret handling but it is not worth since docker-compose is not a HA solution for this project. I propose to reject it.
