### ISSUE TITLE
Broken images

### ISSUE THREAD

**Issue by secobau** [alejandro-colomar/rob_cam#9]
docker-compose.yaml does not work at all so please be careful removing good old images and fix as soon as possible.

**Comment by alejandro-colomar** [comment]
Should be fixed in [v0.6](https://github.com/alejandro-colomar/rob_cam/tree/v0.6).

**Comment by secobau** [comment]
When will alejandrocolomar/rob_cam:rob_0.6 be available?

**Comment by alejandro-colomar** [comment]
> When will alejandrocolomar/rob_cam:rob_0.6 be available?

Build has already been triggered in DockerHub.  Probably in a few hours.

**Comment by alejandro-colomar** [comment]
Bug is still present.  Easiest fix is probably developing a more advanced simulator than returns messages .

**Comment by alejandro-colomar** [comment]
Released oldstable version that fixes this bug by using libalx old UR interface:

[v0.5.6](https://github.com/alejandro-colomar/rob_cam/tree/v0.5.6)
